Try test at two branches

diff --git a/.github/workflows/automatic_ci.yml b/.github/workflows/automatic_ci.yml
--- a/.github/workflows/automatic_ci.yml
+++ b/.github/workflows/automatic_ci.yml
@@ -23,4 +23,28 @@ jobs:
       run: git merge --ff-only origin/main
 
     - name: Run tests
-      run: echo "$(<Readme.md)"
+      run: | 
+        echo "$(<Readme.md)"
+        PR_BRANCH=${GITHUB_HEAD_REF/refs\/heads\//}
+        echo $PR_BRANCH
+    
+  test_on_prod_branches:
+    runs-on: ubuntu-latest
+    needs: build-and-test-the-pull-request
+    strategy:
+        matrix:
+          branch: ['main1', 'main2']
+    
+    steps:
+        - name: Merge changes into main branch
+          run: |
+            git merge --no-ff ${{ github.event.before }} ${{ github.sha }}
+            if [ $? -ne 0 ]; then
+                echo "Merge into ${{ matrix.branch }} failed. Resolve conflicts and try again."
+                exit 1
+            fi
+        - name: Run tests
+          run: |
+            echo "$(<Readme.md)" 
+            echo "${{ matrix.branch }}"
+            echo $PR_BRANCH
